### ISSUE TITLE
Стран нет, это каждую компанию надо гуглить, если не все равно куда уезжать.

### ISSUE THREAD

**Issue by Dmitry-Borodin** [DAlexIV/Petr-The-Engineer#1]
Предлагаю дописать страны, куда компании релокейтят

**Comment by DAlexIV** [comment]
Плюсую, думаю указать конкретную страну)

**Comment by Artemu25** [comment]
и желательно город

**Comment by YapTeam** [comment]
Ну хотя с городами наверное тяжело будет, гуглу тогда надо будет весь мир написать

**Comment by DAlexIV** [comment]
Мне кажется оптимальным решением будет указывать основной город компании.
Так и место немного занимает, да и страна сама понятна становится, что думаете?

**Comment by Dmitry-Borodin** [comment]
Я думаю у больших компаний будет много и городов и стран. И лучше указать и то и другое, просто две колонки добавить. Потом можно будет поиском пройтись и взять все что интересно.

**Comment by DAlexIV** [comment]
@Dmitry-Borodin 
Согласен, наверное реально можно и то и другое указывать.
А страны например помечать флажками, чтобы место не занимать)
